[package]
name = "yozuk-slack"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.136"
serde_derive = "1.0.136"
tokio = { version = "1.17.0", features = ["rt", "macros"] }
reqwest = { version = "0.11", features = ["json"] }
warp = "0.3.2"
yozuk = "0.5.0"
yozuk-bundle = "0.5.0"
yozuk-sdk = "0.2.0"
anyhow = "1.0.56"
